CREATE DATABASE LIVRARIA;

CREATE TABLE LIVRO(
	IDlivro SERIAL PRIMARY KEY,
	nome VARCHAR NOT NULL,
	num_pag INT,
	preco NUMERIC(7,2),
	ano_public INT
);

CREATE TYPE sex AS ENUM('Masc','Fem','Outro');

CREATE TABLE AUTOR(
	IDautor SERIAL PRIMARY KEY,
	nome VARCHAR NOT NULL,
	sexo SEX
);

CREATE TYPE estados AS ENUM('AC','AM','RR','PA','RO','AP','MT','MS','MA','TO','DF','GO','PI','RN','PB','PE','AL','SE','CE','BA','MG','ES','SP','RJ','PR','SC','RS');

CREATE TABLE EDITORA(
	IDeditora SERIAL PRIMARY KEY,
	nome VARCHAR NOT NULL,
	estado ESTADOS
);

CREATE TABLE ASS_EDITORA_LIVRO(
	ID_livro INT,
	ID_editora INT,
	CONSTRAINT FK_ASS_EDITORA_LIVRO_livro
	FOREIGN KEY(ID_livro) 
	REFERENCES LIVRO(IDlivro),
	CONSTRAINT FK_ASS_EDITORA_LIVRO_editora
	FOREIGN KEY(ID_editora) 
	REFERENCES EDITORA(IDeditora),
	PRIMARY KEY (ID_livro,ID_editora)
);

CREATE TABLE ASS_EDITORA_AUTOR(
	ID_autor INT,
	ID_editora INT,
	CONSTRAINT FK_ASS_EDITORA_LIVRO_autor
	FOREIGN KEY(ID_autor) 
	REFERENCES AUTOR(IDautor),
	CONSTRAINT FK_ASS_EDITORA_LIVRO_editora
	FOREIGN KEY(ID_editora) 
	REFERENCES EDITORA(IDeditora),
	PRIMARY KEY (ID_autor,ID_editora)
);

CREATE TABLE ESTOQUE(
	ID_livro INT,
	quant INT,
	CONSTRAINT FK_ESTOQUE_livro
	FOREIGN KEY(ID_livro) 
	REFERENCES LIVRO(IDlivro)
);

CREATE TABLE PESSOA(
	nome VARCHAR NOT NULL,
	sobrenome VARCHAR NOT NULL,
	cpf VARCHAR,
	sexo SEX
);

CREATE TABLE CARGO(
	IDcargo SERIAL PRIMARY KEY,
	nome VARCHAR,
	salario NUMERIC(7,2)
);

CREATE TABLE FUNCIONARIO(
	IDfuncionario SERIAL PRIMARY KEY,
	ID_cargo INT,
	CONSTRAINT FK_FUNCIONARIO_cargo
	FOREIGN KEY(ID_cargo) 
	REFERENCES CARGO(IDcargo)
) INHERITS(PESSOA);

CREATE TABLE ITEM(
	IDitem SERIAL PRIMARY KEY,
	ID_carrinho INT,
	ID_livro INT,
	quant INT,
	CONSTRAINT FK_ITEM_livro
	FOREIGN KEY (ID_livro)
	REFERENCES LIVRO(IDlivro)
);

CREATE TABLE CARRINHO(
	IDcarrinho SERIAL PRIMARY KEY,
	ID_item INT,
	CONSTRAINT FK_CARRINHO_item
	FOREIGN KEY(ID_item)
	REFERENCES ITEM(IDitem)	
);

CREATE TABLE CLIENTE(
	IDcliente SERIAL PRIMARY KEY,
	ID_carrinho INT,
	CONSTRAINT FK_CLIENTE_carrinho
	FOREIGN KEY (ID_carrinho)
	REFERENCES CARRINHO(IDcarrinho)
) INHERITS(PESSOA);

ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_carrinho FOREIGN KEY (ID_carrinho) REFERENCES CARRINHO(IDcarrinho);

CREATE TABLE ASS_CARRINHO_ITEM(
	ID_item INT,
	ID_carrinho INT,
	CONSTRAINT FK_ASS_CARRINHO_ITEM_item
	FOREIGN KEY (ID_item)
	REFERENCES ITEM(IDitem),
	CONSTRAINT FK_ASS_CARRINHO_ITEM_carrinho
	FOREIGN KEY (ID_carrinho)
	REFERENCES CARRINHO(IDcarrinho)
);

CREATE TABLE VENDAS(
	ID_cliente INT NOT NULL,
	ID_livro INT NOT NULL,
	quant INT NOT NULL,
	ID_funcionario INT,
	preco_venda INT NOT NULL
);

