

CREATE DATABASE CURSORES;

USE CURSORES;

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT
);

INSERT INTO VENDEDORES 
VALUES(NULL, 'MAFRA',32432,242334,574545);
INSERT INTO VENDEDORES 
VALUES(NULL, 'CLARA',65213,65231,65765);
INSERT INTO VENDEDORES 
VALUES(NULL, 'JOAO',13543,13432,12342);
INSERT INTO VENDEDORES 
VALUES(NULL, 'LILIAN',16541,12321,121312);
INSERT INTO VENDEDORES 
VALUES(NULL, 'ANTONIO',6346437,124211,543534);
INSERT INTO VENDEDORES 
VALUES(NULL, 'GLORIA',2142141,988432,532232);

SELECT * FROM VENDEDORES;

SELECT NOME,
       (JAN+FEV+MAR) AS TOTAL
FROM VENDEDORES;

SELECT NOME,
       (JAN+FEV+MAR) AS TOTAL,
	   TRUNCATE((JAN+FEV+MAR)/3,2) AS MEDIA
FROM VENDEDORES;

CREATE TABLE VEND_TOTAL(
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT,
	TOTAL INT,
	MEDIA INT
);

DELIMITER $

CREATE PROCEDURE INSEREDADOS()
BEGIN
	DECLARE FIM INT DEFAULT 0; /*NUNCA ALTERAR*/
	DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA  INT; /*ALTERAR*/
	DECLARE VNOME VARCHAR(50); /*ALTERAR*/
	
	DECLARE REG CURSOR FOR( /*NUNCA ALTERAR*/
		SELECT NOME, JAN, FEV, MAR FROM VENDEDORES /*ALTERAR*/
	);
	
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1; /*NUNCA ALTERAR*/
	
	OPEN REG; /*NUNCA ALTERAR*/
	
	REPEAT /*NUNCA ALTERAR*/
		
		FETCH REG INTO VNOME, VAR1, VAR2, VAR3; /*ALTERAR VARIAVEIS*/
		IF NOT FIM THEN /*NUNCA ALTERAR*/
			SET VTOTAL = VAR1 + VAR2 + VAR3; /*ACÕES DO CURSOR*/
			SET VMEDIA = VTOTAL / 3;
			INSERT INTO VEND_TOTAL 
			VALUES(VNOME,VAR1,VAR2,VAR3,VTOTAL,VMEDIA);
		END IF;
		
	UNTIL FIM END REPEAT; /*NUNCA ALTERAR*/
	
	CLOSE REG; /*NUNCA ALTERAR*/

END
$

DELIMITER ;

CALL INSEREDADOS();