
/*CLIENTE*/

INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAO@IG.COM','98547-6');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOS@TERA.COM','86664-7');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@GLOBO.COM','75658-5');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','88657-5');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','M',NULL,'99754-7');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','F','JOAO@TERRA.COM','77558-5');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M',NULL,'78558-6');
INSERT INTO CLIENTE VALUES(NULL,'JOAO','M',NULL,'86695-6');

/*ENDERECO*/

INSERT INTO ENDERECO VALUES(NULL,'B. HORIZONTE','RUA A','MG','CENTRO',4);
INSERT INTO ENDERECO VALUES(NULL,'RIO DE JANEIRO','RUA B','RJ','CENTRO',1);
INSERT INTO ENDERECO VALUES(NULL,'SAO PAULO','RUA C','SP','JARDINS',3);
INSERT INTO ENDERECO VALUES(NULL,'RIO DE JANEIRO','RUA B','RJ','ESTACIO',8);
INSERT INTO ENDERECO VALUES(NULL,'B. HORIZONTE','RUA Z','MG','CRUZEIRO',2);
INSERT INTO ENDERECO VALUES(NULL,'RIO DE JANEIRO','RUA X','RJ','FLAMENGO',7);
INSERT INTO ENDERECO VALUES(NULL,'B. HORIZONTE','RUA Z','MG','CRUZEIRO',5);
INSERT INTO ENDERECO VALUES(NULL,'NITERÓI','RUA X','RJ','CENTRO',6);

/*ERROR PQ NÃO PODE REPETIR A CHAVE ESTRANGEIRA ELA É UNICA */
INSERT INTO ENDERECO VALUES(NULL,'NITERÓI','RUA U','RJ','CENTRO',6);

/*TELEFONE*/

INSERT INTO TELEFONE VALUES(NULL,'CEL','85','9955331',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','91','6574565',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','60','8864566',2);
INSERT INTO TELEFONE VALUES(NULL,'CEL','85','5557798',7);
INSERT INTO TELEFONE VALUES(NULL,'COM','91','6765768',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','87','5676765',6);
INSERT INTO TELEFONE VALUES(NULL,'CEL','60','5765547',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','91','8865645',7);
INSERT INTO TELEFONE VALUES(NULL,'RES','91','7555446',7);
INSERT INTO TELEFONE VALUES(NULL,'CEL','86','5788654',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','85','7865644',6);
INSERT INTO TELEFONE VALUES(NULL,'RES','85','5754644',6);

