/*DML*/
DELETE FROM TABELA 
INSERT INTO TABELA VALUES()
UPDATE TABELA SET COLUNA = VALOR 
WHERE LOGICA BOOLEANA
/* DML EM VIEWS 
É PERMITIDO FAZER UPDATE EM VIEW, SE TIVER JOIN NA VIEW

É PERMITIDO DAS AS AÇOES DE DML EM VIEWS SEM JOIN

*/
