
SELECT COUNT(*),DEPARTAMENTO
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO
ORDER BY COUNT(*) ASC;

SELECT NOME
FROM FUNCIONARIOS
WHERE DEPARTAMENTO = 'Roupas' OR DEPARTAMENTO = 'Filmes';

SELECT NOME, EMAIL
FROM FUNCIONARIOS
WHERE (DEPARTAMENTO = 'Lar' OR DEPARTAMENTO = 'Filmes') AND SEXO = 'Feminino';

SELECT NOME
FROM FUNCIONARIOS
WHERE SEXO='Masculino' OR DEPARTAMENTO='Jardim';