
CREATE DATABASE EXERCICIO;

USE EXERCICIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	CPF VARCHAR(15) UNIQUE NOT NULL,
	SEXO ENUM('F','M') NOT NULL,
	EMAIL VARCHAR(30) UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('COM','CEL','RES') NOT NULL,
	DDD VARCHAR(5) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) NOT NULL,
	MODELO VARCHAR(30),
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TINTA(
	IDTINTA INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(30) NOT NULL,
	ID_CARRO INT,
	FOREIGN KEY(ID_CARRO)
	REFERENCES CARRO(IDCARRO)
);

