CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE LIVRO(
	IDLIVRO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	NUM_PAG INT NOT NULL,
	PRECO FLOAT(10,2) NOT NULL,
	ANO_PUBLIC INT NOT NULL

);

CREATE TABLE AUTOR(
	IDAUTOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('F','M')
);


CREATE TABLE EDITORA(
	IDEDITORA INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	ESTADO ENUM('AC','AM','RR','PA','RO','AP','MT','MS','MA','TO','DF','GO','PI','RN','PB','PE','AL','SE','CE','BA','MG','ES','SP','RJ','PR','SC','RS')
);

CREATE TABLE ASS_AUTOR_LIVRO(
	ID_AUTOR INT NOT NULL, /* FOREIGN KEY */
	ID_LIVRO INT NOT NULL, /* FOREIGN KEY */
	PRIMARY KEY(ID_AUTOR,ID_LIVRO)
);

CREATE TABLE ASS_AUTOR_EDITORA(
	ID_AUTOR INT NOT NULL, /* FOREIGN KEY */
	ID_EDITORA INT NOT NULL, /* FOREIGN KEY */
	PRIMARY KEY(ID_AUTOR,ID_EDITORA)
);

ALTER TABLE ASS_AUTOR_LIVRO ADD CONSTRAINT FK_ASS_A_L_LIVRO
FOREIGN KEY(ID_LIVRO) REFERENCES LIVRO(IDLIVRO);

ALTER TABLE ASS_AUTOR_LIVRO ADD CONSTRAINT FK_ASS_A_L_AUTOR
FOREIGN KEY(ID_AUTOR) REFERENCES AUTOR(IDAUTOR);

ALTER TABLE ASS_AUTOR_EDITORA ADD CONSTRAINT FK_ASS_A_E_AUTOR
FOREIGN KEY(ID_AUTOR) REFERENCES AUTOR(IDAUTOR);

ALTER TABLE ASS_AUTOR_EDITORA ADD CONSTRAINT FK_ASS_A_E_EDITORA
FOREIGN KEY(ID_EDITORA) REFERENCES EDITORA(IDEDITORA);

INSERT INTO AUTOR(NOME,SEXO) VALUES('RAFAEL','M');
INSERT INTO AUTOR(NOME,SEXO) VALUES('MAFRA','M');
INSERT INTO AUTOR(NOME,SEXO) VALUES('FELIPE','M');
INSERT INTO AUTOR(NOME,SEXO) VALUES('SILVIO','M');
INSERT INTO AUTOR(NOME,SEXO) VALUES('ANA','F');
INSERT INTO AUTOR(NOME,SEXO) VALUES('LARA','F');
INSERT INTO AUTOR(NOME,SEXO) VALUES('CLARA','F');
INSERT INTO AUTOR(NOME,SEXO) VALUES('BEATRIZ','F');

INSERT INTO LIVRO(NOME,NUM_PAG,PRECO,ANO_PUBLIC) VALUES('LINGUAGEM SQL',325,200.00,2015);
INSERT INTO LIVRO(NOME,NUM_PAG,PRECO,ANO_PUBLIC) VALUES('LINGUAGEM PYTHON',250,130.00,2017);
INSERT INTO LIVRO(NOME,NUM_PAG,PRECO,ANO_PUBLIC) VALUES('LINGUAGEM C++',520,340.00,2012);
INSERT INTO LIVRO(NOME,NUM_PAG,PRECO,ANO_PUBLIC) VALUES('LINGUAGEM C',350,300.00,2010);
INSERT INTO LIVRO(NOME,NUM_PAG,PRECO,ANO_PUBLIC) VALUES('LINGUAGEM JAVA',340,279.99,2016);

INSERT INTO EDITORA(NOME,ESTADO) VALUES('MODERNA','SP');
INSERT INTO EDITORA(NOME,ESTADO) VALUES('SARAIVA','CE');
														   /*A E*/
INSERT INTO ASS_AUTOR_LIVRO(ID_AUTOR,ID_LIVRO) VALUES(2,1);/*2 2*/
INSERT INTO ASS_AUTOR_LIVRO(ID_AUTOR,ID_LIVRO) VALUES(2,5);/*2 2*/
INSERT INTO ASS_AUTOR_LIVRO(ID_AUTOR,ID_LIVRO) VALUES(5,5);/*5 2*/
INSERT INTO ASS_AUTOR_LIVRO(ID_AUTOR,ID_LIVRO) VALUES(3,5);/*3 1*/
INSERT INTO ASS_AUTOR_LIVRO(ID_AUTOR,ID_LIVRO) VALUES(1,2);/*1 1*/
INSERT INTO ASS_AUTOR_LIVRO(ID_AUTOR,ID_LIVRO) VALUES(6,3);/*6 1*/
INSERT INTO ASS_AUTOR_LIVRO(ID_AUTOR,ID_LIVRO) VALUES(4,4);/*4 1*/


INSERT INTO ASS_AUTOR_EDITORA VALUES(1,1);
INSERT INTO ASS_AUTOR_EDITORA VALUES(2,2);
INSERT INTO ASS_AUTOR_EDITORA VALUES(3,1);
INSERT INTO ASS_AUTOR_EDITORA VALUES(5,2);
INSERT INTO ASS_AUTOR_EDITORA VALUES(6,1);
INSERT INTO ASS_AUTOR_EDITORA VALUES(4,1);


SELECT A.NOME AS AUTOR, 
       L.NOME AS LIVRO, 
	   L.ANO_PUBLIC AS PUBLICACAO
FROM AUTOR AS A
INNER JOIN ASS_AUTOR_LIVRO AS ASS
ON A.IDAUTOR = ASS.ID_AUTOR
INNER JOIN LIVRO AS L
ON ASS.ID_LIVRO = L.IDLIVRO
ORDER BY L.NOME ASC,A.NOME ASC;


SELECT A.NOME AS AUTOR, 
       L.NOME AS LIVRO, 
	   L.ANO_PUBLIC AS PUBLICACAO,
	   E.NOME AS EDITORA,
	   E.ESTADO
FROM AUTOR AS A
INNER JOIN ASS_AUTOR_LIVRO AS ASS
ON A.IDAUTOR = ASS.ID_AUTOR
INNER JOIN LIVRO AS L
ON ASS.ID_LIVRO = L.IDLIVRO
INNER JOIN ASS_AUTOR_EDITORA AS ASS2
ON ASS2.ID_AUTOR = A.IDAUTOR
INNER JOIN EDITORA AS E
ON E.IDEDITORA = ASS2.ID_EDITORA
ORDER BY L.NOME ASC,A.NOME ASC;

DELIMITER $

CREATE PROCEDURE AUTORES_LIVRO(NOME_LIVRO VARCHAR(30))
BEGIN
	SELECT A.NOME
	FROM LIVRO AS L
	INNER JOIN ASS_AUTOR_LIVRO AS ASS
	ON ASS.ID_LIVRO = L.IDLIVRO
	INNER JOIN AUTOR AS A
	ON ASS.ID_AUTOR = A.IDAUTOR
	WHERE L.NOME = NOME_LIVRO
	ORDER BY L.NOME ASC,A.NOME;
END
$

CREATE PROCEDURE QUANT_AUTORES_LIVRO(NOME_LIVRO VARCHAR(30))
BEGIN
	SELECT COUNT(*) AS 'QUANTIDADE'
	FROM LIVRO AS L
	INNER JOIN ASS_AUTOR_LIVRO AS ASS
	ON ASS.ID_LIVRO = L.IDLIVRO
	INNER JOIN AUTOR AS A
	ON ASS.ID_AUTOR = A.IDAUTOR
	WHERE L.NOME = NOME_LIVRO
	GROUP BY L.NOME;
END
$

DELIMITER ;

CALL AUTORES_LIVRO('LINGUAGEM JAVA');
CALL AUTORES_LIVRO('LINGUAGEM PYTHON');
CALL QUANT_AUTORES_LIVRO('LINGUAGEM JAVA');
CALL QUANT_AUTORES_LIVRO('LINGUAGEM PYTHON');

