
USE PROJETO;

SELECT NOME, 
       JANEIRO,
	   FEVEREIRO,
	   MARCO,
	   (JANEIRO+FEVEREIRO+MARCO) AS 'TOTAL',
	   TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS 'MEDIA'
FROM VENDEDORES;

SELECT NOME, 
       JANEIRO,
	   FEVEREIRO,
	   MARCO,
	   (JANEIRO+FEVEREIRO+MARCO) AS 'TOTAL',
	   (JANEIRO+FEVEREIRO+MARCO)*.25 AS 'DECONTO',
	   TRUNCATE((JANEIRO+FEVEREIRO+MARCO)-(JANEIRO+FEVEREIRO+MARCO)*.25,2) AS 'MEDIA'
FROM VENDEDORES;