SELECT C.NOME,C.CPF,C.SEXO,E.CIDADE
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE =E.ID_CLIENTE
ORDER BY C.NOME,C.CPF DESC;


SELECT C.NOME,C.CPF,C.SEXO,E.CIDADE
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE =E.ID_CLIENTE
ORDER BY C.NOME,C.CPF ASC;

SELECT C.NOME,C.CPF,C.SEXO,E.CIDADE
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE =E.ID_CLIENTE
ORDER BY 4;