/*COMANDO SELECT */
USE PROJETO;

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';

SELECT 'FELIPE MAFRA' AS PROFESSOR;

SELECT NOME,SEXO,EMAIL FROM CLIENTE;

SELECT ENDERECO, NOME FROM CLIENTE;

/*NUNCA UTILIZE:
	SELECT * FROM CLIENTE;

POIS MUITOS DADOS DESNECESSÁRIOS SERAM PUXADOS DO BANCO DE DADOS
ATRAPALHANDO A ESPERIÊNCIA DO USUÁRIO, COM LENTIDÃO.

*/