
/*VENDEDOR Q VENDEU MENOS EM MARCO E SEU NOME

NOME E O VALOR QUE VENDEU MAIS EM MARCO

QUEM VENDEU MAIS QUE O VALOR MEDIO DE FEV
*/

SELECT NOME,MARCO
FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);

SELECT NOME,MARCO
FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);

SELECT NOME,FEVEREIRO
FROM VENDEDORES
WHERE FEVEREIRO >= (SELECT AVG(FEVEREIRO) FROM VENDEDORES);

SELECT NOME,MARCO
FROM VENDEDORES
WHERE MARCO >= (SELECT AVG(MARCO) FROM VENDEDORES);