

SELECT C.NOME,
       C.SEXO,
	   IFNULL(C.EMAIL,'SEM EMAIL') AS 'EMAIL',
	   T.TIPO,
	   T.DDD,
	   T.NUMERO,
	   E.BAIRRO,
	   E.CIDADE,
	   E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

/* CRIANDO UMA VIEW */

CREATE VIEW V_RELATORIO AS
SELECT C.NOME,
       C.SEXO,
	   IFNULL(C.EMAIL,'SEM EMAIL') AS 'EMAIL',
	   T.TIPO,
	   T.DDD,
	   T.NUMERO,
	   E.BAIRRO,
	   E.CIDADE,
	   E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;



