/* CONECTANDO A UM BANCO */

USE EMPRESA
GO

CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(30) UNIQUE
)
GO


/* CONSTRAINTS */

ALTER TABLE ALUNO 
ADD CONSTRAINT CK_SEXO 
CHECK (SEXO IN('M','F'))
GO


/* 1 x 1 */

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(100,10),
	BAIRRO VARCHAR(30),
	UF CHAR(2) NOT NULL
	CHECK (UF IN('RJ','SP','MG')),
	ID_ALUNO INT UNIQUE

)
GO

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY(ID_ALUNO)
REFERENCES ALUNO(IDALUNO)
GO

/* COMANDOS DE DESCRICAO */

/*SP_ STORAGE PROCEDURE */

SP_COLUMNS ENDERECO
GO

SP_HELP ALUNO
GO
 
INSERT INTO ALUNO 
VALUES('ANDRE','M','1981/12/09','ANDRE@IG.COM')
INSERT INTO ALUNO 
VALUES('ANA','F','1978/12/09','ANA@IG.COM')
INSERT INTO ALUNO 
VALUES('RUI','M','1965/07/09','RUI@IG.COM')
INSERT INTO ALUNO 
VALUES('JOAO','M','2002/11/09','JOAO@IG.COM')
GO

SELECT * FROM ALUNO GO

INSERT INTO ENDERECO VALUES('FLAMENGO','RJ',1)
INSERT INTO ENDERECO VALUES('MORUMBI','SP',2)
INSERT INTO ENDERECO VALUES('CENTRO','MG',4)
INSERT INTO ENDERECO VALUES('CENTRO','SP',3)
GO

SELECT * FROM ENDERECO GO

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_ALUNO INT,
	CHECK(TIPO IN('RES','COM','CEL'))
)
GO

INSERT INTO TELEFONE VALUES('CEL','7899889',1)
INSERT INTO TELEFONE VALUES('RES','4325444',1)
INSERT INTO TELEFONE VALUES('COM','4354354',2)
INSERT INTO TELEFONE VALUES('CEL','2344556',2)
GO

SELECT * FROM TELEFONE GO

/* " " EM SQL SERVER, NÃO FUNCIONA ' '*/
SELECT GETDATE() AS "DATE"
GO

/* CLAUSULA AMBIGUA */
DELETE FROM TELEFONE WHERE IDTELEFONE > 4
SELECT A.NOME,
       ISNULL(T.TIPO,'SEM') AS "TIPO",
	   ISNULL(T.NUMERO,'SEM') AS "NUMERO",
	   E.BAIRRO,
	   E.UF
FROM ALUNO A
LEFT JOIN TELEFONE T
ON A.IDALUNO = T.ID_ALUNO
INNER JOIN ENDERECO E
ON A.IDALUNO = E.ID_ALUNO
GO

SELECT NOME,NASCIMENTO
FROM ALUNO
GO

/* DATAS */

SELECT NOME,GETDATE() AS DIA_HORA
FROM ALUNO
GO
/*DAY, MONTH, YEAR*/
SELECT NOME,
       DATEDIFF(MONTH,NASCIMENTO,GETDATE()) AS DIAS_VIDA
FROM ALUNO
GO

SELECT NOME,
       DATENAME(MONTH,NASCIMENTO) AS "MONTH"
FROM ALUNO
GO

SELECT NOME,
       DATEPART(MONTH,NASCIMENTO) AS "MONTH"
FROM ALUNO
GO

/* DATEADD */

SELECT NOME,
       DATEADD(YEAR,30,NASCIMENTO) AS "MONTH"
FROM ALUNO
GO

/*CONVERSAO DE DADOS*/

SELECT 1 + '10' /*SOMA*/
GO
SELECT '1' + '10'/*CONCATENA*/
GO
/*CONVERTER DADOS*/

SELECT CAST('1' AS INT) + CAST('1' AS INT)
GO

SELECT NOME,
NASCIMENTO
FROM ALUNO
GO

SELECT NOME,
		CAST(DAY(NASCIMENTO) AS VARCHAR) + '/' + CAST(MONTH(NASCIMENTO) AS VARCHAR) + '/' + CAST(YEAR(NASCIMENTO) AS VARCHAR) AS "DATA"
FROM ALUNO
GO

/* CHARINDEX */

SELECT NOME,
       CHARINDEX('A',NOME) AS INDICE
FROM ALUNO
GO

SELECT NOME,
       CHARINDEX('A',NOME,2) AS INDICE
FROM ALUNO
GO

/*BULK INSERT - IMPORTACAO DE ARQUIVOS */

CREATE TABLE LANCAMENTO_CONTABIL(
	CONTA INT,
	VALOR INT,
	DEB_CRED CHAR(1)
)
GO

SELECT * FROM LANCAMENTO_CONTABIL GO

BULK INSERT LANCAMENTO_CONTABIL
FROM 'C:\Users\pedro\Downloads\original.txt'
WITH
(
	FIRSTROW = 2,
	DATAFILETYPE = 'char',
	FIELDTERMINATOR = '\t',
	ROWTERMINATOR = '\n'
)
GO

/* MINHA SOLUCAO */
CREATE VIEW V_RELATORIO AS
SELECT CONTA,
		SUM(VALOR) AS "SOMA",
		CHARINDEX('D',DEB_CRED) AS "DEBITO" /*incompleto*/
FROM LANCAMENTO_CONTABIL
GROUP BY DEB_CRED,CONTA
ORDER BY CONTA
GO

SELECT R.CONTA,
       (R.SOMA+E.SOMA)/*incompleto*/
FROM V_RELATORIO AS "R"
LEFT JOIN V_RELATORIO AS "E"
ON R.DEBITO!=E.DEBITO
GO

/* SOLUÇÃO */

SELECT CONTA,
       VALOR,
	   CHARINDEX('C',DEB_CRED) AS "CREDITO",
	   CHARINDEX('D',DEB_CRED) AS "DEBITO"
FROM LANCAMENTO_CONTABIL

SELECT CONTA,
		SUM(VALOR) AS "SOMA",
		CHARINDEX('C',DEB_CRED)*2 - 1 AS "MULTIPLICADOR"
FROM LANCAMENTO_CONTABIL
GROUP BY DEB_CRED,CONTA
ORDER BY CONTA
GO

SELECT CONTA,
       SUM(VALOR *(CHARINDEX('C',DEB_CRED)*2 - 1)) AS SALDO
FROM LANCAMENTO_CONTABIL
GROUP BY CONTA
GO

