COPY( SELECT
CASE
    WHEN (action LIKE 'lookup') THEN 1
    WHEN (action LIKE 'search_results') THEN 2
    WHEN (action LIKE 'personalize') THEN 3
    WHEN (action LIKE 'index') THEN 4
    WHEN (action LIKE 'similar_listings') THEN 5
    WHEN (action LIKE 'ajax_refresh_subtotal') THEN 6
    WHEN (action LIKE 'show') THEN 7
    WHEN (action LIKE 'header_userpic') THEN 8
    WHEN (action LIKE 'ask_question') THEN 9
    WHEN (action LIKE 'other_hosting_reviews_first') THEN 10
    WHEN (action LIKE 'hosting_social_proof') THEN 11
    WHEN (action LIKE 'decision_tree') THEN 12
    WHEN (action LIKE 'recent_reservations') THEN 13
    WHEN (action LIKE 'faq_experiment_ids') THEN 14
    WHEN (action LIKE 'multi') THEN 15
    WHEN (action LIKE 'active') THEN 16
    WHEN (action LIKE 'dashboard') THEN 17
    WHEN (action LIKE 'create') THEN 18
    WHEN (action LIKE 'confirm_email') THEN 19
    WHEN (action LIKE 'show_personalize') THEN 20
    WHEN (action LIKE 'verify') THEN 21
    WHEN (action LIKE 'pending') THEN 22
    WHEN (action LIKE 'requested') THEN 23
    WHEN (action LIKE 'concierge') THEN 24
    WHEN (action LIKE 'faq') THEN 25
    WHEN (action LIKE 'clear_reservation') THEN 26
    WHEN (action LIKE 'cancellation_policies') THEN 27
    WHEN (action LIKE 'track_page_view') THEN 28
    WHEN (action LIKE 'update') THEN 29
    WHEN (action LIKE 'my') THEN 30
    WHEN (action LIKE 'campaigns') THEN 31
    WHEN (action LIKE 'notifications') THEN 32
    WHEN (action LIKE 'listings') THEN 33
    WHEN (action LIKE 'unavailabilities') THEN 34
    WHEN (action LIKE 'ajax_lwlb_contact') THEN 35
    WHEN (action LIKE 'ajax_check_dates') THEN 36
    WHEN (action LIKE 'qt2') THEN 37
    WHEN (action LIKE 'request_new_confirm_email') THEN 38
    WHEN (action LIKE 'ajax_photo_widget_form_iframe') THEN 39
    WHEN (action LIKE 'facebook_auto_login') THEN 40
    WHEN (action LIKE 'identity') THEN 41
    WHEN (action LIKE 'qt_reply_v2') THEN 42
    WHEN (action LIKE 'travel_plans_current') THEN 43
    WHEN (action LIKE 'complete_status') THEN 44
    WHEN (action LIKE 'populate_from_facebook') THEN 45
    WHEN (action LIKE 'kba_update') THEN 46
    WHEN (action LIKE 'kba') THEN 47
    WHEN (action LIKE 'login') THEN 48
    WHEN (action LIKE 'authenticate') THEN 49
    WHEN (action LIKE 'calendar_tab_inner2') THEN 50
    WHEN (action LIKE 'other_hosting_reviews') THEN 51
    WHEN (action LIKE 'social_connections') THEN 52
    WHEN (action LIKE 'relationship') THEN 53
    WHEN (action LIKE '15') THEN 54
    WHEN (action LIKE 'collections') THEN 55
    WHEN (action LIKE '12') THEN 56
    WHEN (action LIKE 'jumio_redirect') THEN 57
    WHEN (action LIKE 'jumio_token') THEN 58
    WHEN (action LIKE 'login_modal') THEN 59
    WHEN (action LIKE 'domains') THEN 60
    WHEN (action LIKE 'toggle_archived_thread') THEN 61
    WHEN (action LIKE 'search') THEN 62
    WHEN (action LIKE 'edit_verification') THEN 63
    WHEN (action LIKE 'edit') THEN 64
    WHEN (action LIKE 'ajax_ldp') THEN 65
    WHEN (action LIKE 'connect') THEN 66
    WHEN (action LIKE 'account') THEN 67
    WHEN (action LIKE 'delete') THEN 68
    WHEN (action LIKE 'phone_number_widget') THEN 69
    WHEN (action LIKE 'callback') THEN 70
    WHEN (action LIKE 'signup_modal') THEN 71
    WHEN (action LIKE '10') THEN 72
    WHEN (action LIKE 'open_graph_setting') THEN 73
    WHEN (action LIKE 'reviews') THEN 74
    WHEN (action LIKE 'signup_login') THEN 75
    WHEN (action LIKE 'payment_instruments') THEN 76
    WHEN (action LIKE 'payment_methods') THEN 77
    WHEN (action LIKE 'pay') THEN 78
    WHEN (action LIKE 'unread') THEN 79
    WHEN (action LIKE 'at_checkpoint') THEN 80
    WHEN (action LIKE 'push_notification_callback') THEN 81
    WHEN (action LIKE 'faq_category') THEN 82
    WHEN (action LIKE 'localization_settings') THEN 83
    WHEN (action LIKE 'update_notifications') THEN 84
    WHEN (action LIKE 'manage_listing') THEN 85
    WHEN (action LIKE 'set_user') THEN 86
    WHEN (action LIKE 'references') THEN 87
    WHEN (action LIKE 'languages_multiselect') THEN 88
    WHEN (action LIKE 'salute') THEN 89
    WHEN (action LIKE 'rentals') THEN 90
    WHEN (action LIKE 'currencies') THEN 91
    WHEN (action LIKE 'new') THEN 92
    WHEN (action LIKE 'position') THEN 93
    WHEN (action LIKE 'populate_help_dropdown') THEN 94
    WHEN (action LIKE 'popular') THEN 95
    WHEN (action LIKE 'popular_listing') THEN 96
    WHEN (action LIKE 'listing') THEN 97
    WHEN (action LIKE 'available') THEN 98
    WHEN (action LIKE 'glob') THEN 99
    WHEN (action LIKE 'this_hosting_reviews') THEN 100
    WHEN (action LIKE 'widget') THEN 101
    WHEN (action LIKE 'complete') THEN 102
    WHEN (action LIKE 'profile_pic') THEN 103
    WHEN (action LIKE 'signature') THEN 104
    WHEN (action LIKE 'apply_reservation') THEN 105
    WHEN (action LIKE 'ajax_statsd') THEN 106
    WHEN (action LIKE 'travel') THEN 107
    WHEN (action LIKE 'tos_confirm') THEN 108
    WHEN (action LIKE 'uptodate') THEN 109
    WHEN (action LIKE 'ajax_payout_options_by_country') THEN 110
    WHEN (action LIKE 'payout_preferences') THEN 111
    WHEN (action LIKE 'payout_update') THEN 112
    WHEN (action LIKE 'ajax_payout_edit') THEN 113
    WHEN (action LIKE 'pending_tickets') THEN 114
    WHEN (action LIKE 'issue') THEN 115
    WHEN (action LIKE 'contact_new') THEN 116
    WHEN (action LIKE 'itinerary') THEN 117
    WHEN (action LIKE 'receipt') THEN 118
    WHEN (action LIKE 'update_hide_from_search_engines') THEN 119
    WHEN (action LIKE 'settings') THEN 120
    WHEN (action LIKE 'privacy') THEN 121
    WHEN (action LIKE 'reviews_new') THEN 122
    WHEN (action LIKE 'add_guests') THEN 123
    WHEN (action LIKE 'ajax_image_upload') THEN 124
    WHEN (action LIKE 'qt_with') THEN 125
    WHEN (action LIKE 'webcam_upload') THEN 126
    WHEN (action LIKE 'friends') THEN 127
    WHEN (action LIKE 'ajax_google_translate_description') THEN 128
    WHEN (action LIKE 'trust') THEN 129
    WHEN (action LIKE 'guarantee') THEN 130
    WHEN (action LIKE 'supported') THEN 131
    WHEN (action LIKE 'countries') THEN 132
    WHEN (action LIKE 'status') THEN 133
    WHEN (action LIKE 'upload') THEN 134
    WHEN (action LIKE 'authorize') THEN 135
    WHEN (action LIKE 'rate') THEN 136
    WHEN (action LIKE 'remove_dashboard_alert') THEN 137
    WHEN (action LIKE 'ajax_get_results') THEN 138
    WHEN (action LIKE 'recommend') THEN 139
    WHEN (action LIKE 'change_currency') THEN 140
    WHEN (action LIKE 'transaction_history_paginated') THEN 141
    WHEN (action LIKE 'transaction_history') THEN 142
    WHEN (action LIKE 'set_password') THEN 143
    WHEN (action LIKE 'cancel') THEN 144
    WHEN (action LIKE 'phone_verification_modal') THEN 145
    WHEN (action LIKE 'submit_contact') THEN 146
    WHEN (action LIKE 'detect_fb_session') THEN 147
    WHEN (action LIKE 'tell_a_friend') THEN 148
    WHEN (action LIKE 'change') THEN 149
    WHEN (action LIKE 'clickthrough') THEN 150
    WHEN (action LIKE 'multi_message_attributes') THEN 151
    WHEN (action LIKE 'update_friends_display') THEN 152
    WHEN (action LIKE 'my_listings') THEN 153
    WHEN (action LIKE 'email_itinerary_colorbox') THEN 154
    WHEN (action LIKE 'mobile_landing_page') THEN 155
    WHEN (action LIKE 'create_ach') THEN 156
    WHEN (action LIKE 'country_options') THEN 157
    WHEN (action LIKE '11') THEN 158
    WHEN (action LIKE 'host_2013') THEN 159
    WHEN (action LIKE 'terms') THEN 160
    WHEN (action LIKE 'multi_message') THEN 161
    WHEN (action LIKE 'ajax_send_message') THEN 162
    WHEN (action LIKE 'airbnb_picks') THEN 163
    WHEN (action LIKE 'friends_new') THEN 164
    WHEN (action LIKE 'reputation') THEN 165
    WHEN (action LIKE 'complete_redirect') THEN 166
    WHEN (action LIKE 'toggle_starred_thread') THEN 167
    WHEN (action LIKE 'email_share') THEN 168
    WHEN (action LIKE 'email_wishlist') THEN 169
    WHEN (action LIKE 'destroy') THEN 170
    WHEN (action LIKE 'add_note') THEN 171
    WHEN (action LIKE 'overview') THEN 172
    WHEN (action LIKE 'requirements') THEN 173
    WHEN (action LIKE 'update_reservation_requirements') THEN 174
    WHEN (action LIKE 'image_order') THEN 175
    WHEN (action LIKE 'review_page') THEN 176
    WHEN (action LIKE 'ajax_worth') THEN 177
    WHEN (action LIKE 'place_worth') THEN 178
    WHEN (action LIKE 'google_importer') THEN 179
    WHEN (action LIKE 'change_availability') THEN 180
    WHEN (action LIKE 'hospitality') THEN 181
    WHEN (action LIKE 'change_password') THEN 182
    WHEN (action LIKE 'feed') THEN 183
    WHEN (action LIKE 'host_summary') THEN 184
    WHEN (action LIKE 'ajax_price_and_availability') THEN 185
    WHEN (action LIKE 'jumio') THEN 186
    WHEN (action LIKE 'guest_booked_elsewhere') THEN 187
    WHEN (action LIKE 'about_us') THEN 188
    WHEN (action LIKE 'founders') THEN 189
    WHEN (action LIKE 'travel_plans_previous') THEN 190
    WHEN (action LIKE 'why_host') THEN 191
    WHEN (action LIKE 'hospitality_standards') THEN 192
    WHEN (action LIKE 'social') THEN 193
    WHEN (action LIKE 'recommendations') THEN 194
    WHEN (action LIKE 'update_cached') THEN 195
    WHEN (action LIKE 'become_user') THEN 196
    WHEN (action LIKE 'departments') THEN 197
    WHEN (action LIKE 'department') THEN 198
    WHEN (action LIKE 'office_location') THEN 199
    WHEN (action LIKE 'photography') THEN 200
    WHEN (action LIKE 'preapproval') THEN 201
    WHEN (action LIKE 'maybe_information') THEN 202
    WHEN (action LIKE 'toggle_availability') THEN 203
    WHEN (action LIKE 'payoneer_account_redirect') THEN 204
    WHEN (action LIKE 'forgot_password') THEN 205
    WHEN (action LIKE 'new_host') THEN 206
    WHEN (action LIKE 'payoneer_signup_complete') THEN 207
    WHEN (action LIKE 'ajax_google_translate') THEN 208
    WHEN (action LIKE 'onenight') THEN 209
    WHEN (action LIKE 'approve') THEN 210
    WHEN (action LIKE 'nyan') THEN 211
    WHEN (action LIKE 'booking') THEN 212
    WHEN (action LIKE 'payout_delete') THEN 213
    WHEN (action LIKE 'change_default_payout') THEN 214
    WHEN (action LIKE 'envoy_bank_details_redirect') THEN 215
    WHEN (action LIKE 'respond') THEN 216
    WHEN (action LIKE 'request_photography') THEN 217
    WHEN (action LIKE 'zendesk_login_jwt') THEN 218
    WHEN (action LIKE 'ajax_photo_widget') THEN 219
    WHEN (action LIKE 'message') THEN 220
    WHEN (action LIKE 'southern-europe') THEN 221
    WHEN (action LIKE 'life') THEN 222
    WHEN (action LIKE 'press_release') THEN 223
    WHEN (action LIKE 'media_resources') THEN 224
    WHEN (action LIKE 'press_news') THEN 225
    WHEN (action LIKE 'referrer_status') THEN 226
    WHEN (action LIKE 'create_multiple') THEN 227
    WHEN (action LIKE 'load_more') THEN 228
    WHEN (action LIKE 'create_paypal') THEN 229
    WHEN (action LIKE 'locale_from_host') THEN 230
    WHEN (action LIKE 'terms_and_conditions') THEN 231
    WHEN (action LIKE 'invalid_action') THEN 232
    WHEN (action LIKE 'photography_update') THEN 233
    WHEN (action LIKE 'badge') THEN 234
    WHEN (action LIKE 'apply') THEN 235
    WHEN (action LIKE 'redirect') THEN 236
    WHEN (action LIKE 'pricing') THEN 237
    WHEN (action LIKE 'apply_code') THEN 238
    WHEN (action LIKE 'slideshow') THEN 239
    WHEN (action LIKE 'locations') THEN 240
    WHEN (action LIKE 'ajax_google_translate_reviews') THEN 241
    WHEN (action LIKE 'new_session') THEN 242
    WHEN (action LIKE 'has_profile_pic') THEN 243
    WHEN (action LIKE 'sublets') THEN 244
    WHEN (action LIKE 'wishlists') THEN 245
    WHEN (action LIKE 'reservation') THEN 246
    WHEN (action LIKE 'localized') THEN 247
    WHEN (action LIKE 'home_safety_landing') THEN 248
    WHEN (action LIKE 'click') THEN 249
    WHEN (action LIKE 'how_it_works') THEN 250
    WHEN (action LIKE 'ajax_get_referrals_amt') THEN 251
    WHEN (action LIKE 'phone_verification') THEN 252
    WHEN (action LIKE 'satisfy') THEN 253
    WHEN (action LIKE 'city_count') THEN 254
    WHEN (action LIKE 'recommendation_page') THEN 255
    WHEN (action LIKE 'press_content') THEN 256
    WHEN (action LIKE 'guest_billing_receipt') THEN 257
    WHEN (action LIKE 'ajax_payout_split_edit') THEN 258
    WHEN (action LIKE 'print_confirmation') THEN 259
    WHEN (action LIKE 'envoy_form') THEN 260
    WHEN (action LIKE 'ajax_special_offer_dates_available') THEN 261
    WHEN (action LIKE 'ajax_referral_banner_experiment_type') THEN 262
    WHEN (action LIKE 'patch') THEN 263
    WHEN (action LIKE 'questions') THEN 264
    WHEN (action LIKE 'home_safety_terms') THEN 265
    WHEN (action LIKE 'track_activity') THEN 266
    WHEN (action LIKE 'check') THEN 267
    WHEN (action LIKE 'sldf') THEN 268
    WHEN (action LIKE 'recommended_listings') THEN 269
    WHEN (action LIKE 'mobile_oauth_callback') THEN 270
    WHEN (action LIKE 'show_code') THEN 271
    WHEN (action LIKE 'signed_out_modal') THEN 272
    WHEN (action LIKE 'plaxo_cb') THEN 273
    WHEN (action LIKE 'views') THEN 274
    WHEN (action LIKE 'friend_listing') THEN 275
    WHEN (action LIKE 'ajax_referral_banner_type') THEN 276
    WHEN (action LIKE 'deactivate') THEN 277
    WHEN (action LIKE 'sync') THEN 278
    WHEN (action LIKE 'social-media') THEN 279
    WHEN (action LIKE 'united-states') THEN 280
    WHEN (action LIKE 'email_by_key') THEN 281
    WHEN (action LIKE 'disaster_action') THEN 282
    WHEN (action LIKE 'views_campaign') THEN 283
    WHEN (action LIKE 'update_message') THEN 284
    WHEN (action LIKE 'spoken_languages') THEN 285
    WHEN (action LIKE 'use_mobile_site') THEN 286
    WHEN (action LIKE 'deauthorize') THEN 287
    WHEN (action LIKE 'special_offer') THEN 288
    WHEN (action LIKE 'top_destinations') THEN 289
    WHEN (action LIKE 'create_airbnb') THEN 290
    WHEN (action LIKE 'handle_vanity_url') THEN 291
    WHEN (action LIKE 'impressions') THEN 292
    WHEN (action LIKE 'message_to_host_focus') THEN 293
    WHEN (action LIKE 'cancellation_policy_click') THEN 294
    WHEN (action LIKE 'message_to_host_change') THEN 295
    WHEN (action LIKE 'agree_terms_check') THEN 296
    WHEN (action LIKE 'read_policy_click') THEN 297
    WHEN (action LIKE 'phone_verification_success') THEN 298
    WHEN (action LIKE 'phone_verification_number_sucessfully_submitted') THEN 299
    WHEN (action LIKE 'phone_verification_number_submitted_for_sms') THEN 300
    WHEN (action LIKE 'phone_verification_phone_number_removed') THEN 301
    WHEN (action LIKE 'endpoint_error') THEN 302
    WHEN (action LIKE 'p4_refund_policy_terms') THEN 303
    WHEN (action LIKE 'apply_coupon_error_type') THEN 304
    WHEN (action LIKE 'apply_coupon_error') THEN 305
    WHEN (action LIKE 'apply_coupon_click') THEN 306
    WHEN (action LIKE 'coupon_field_focus') THEN 307
    WHEN (action LIKE 'coupon_code_click') THEN 308
    WHEN (action LIKE 'agree_terms_uncheck') THEN 309
    WHEN (action LIKE 'p4_terms') THEN 310
    WHEN (action LIKE 'phone_verification_call_taking_too_long') THEN 311
    WHEN (action LIKE 'phone_verification_number_submitted_for_call') THEN 312
    WHEN (action LIKE 'phone_verification_error') THEN 313
    WHEN (action LIKE 'apply_coupon_click_success') THEN 314
    WHEN (action LIKE 'set_default') THEN 315
    WHEN (action LIKE 'update_country_of_residence') THEN 316
    WHEN (action LIKE 'open_hard_fallback_modal') THEN 317
    WHEN (action LIKE 'tos_2014') THEN 318
    WHEN (action LIKE 'views_campaign_rules') THEN 319
    WHEN (action LIKE 'weibo_signup_referral_finish') THEN 320
    WHEN (action LIKE 'signup_weibo_referral') THEN 321
    WHEN (action LIKE 'similar_listings_v2') THEN 322
    WHEN (action LIKE 'confirmation') THEN 323
    WHEN (action LIKE 'signup_weibo') THEN 324
    WHEN (action LIKE 'acculynk_load_pin_pad') THEN 325
    WHEN (action LIKE 'acculynk_bin_check_success') THEN 326
    WHEN (action LIKE 'acculynk_session_obtained') THEN 327
    WHEN (action LIKE 'acculynk_pin_pad_inactive') THEN 328
    WHEN (action LIKE 'reactivate') THEN 329
    WHEN (action LIKE 'airbrb') THEN 330
    WHEN (action LIKE 'desks') THEN 331
    WHEN (action LIKE 'sandy') THEN 332
    WHEN (action LIKE 'unsubscribe') THEN 333
    WHEN (action LIKE 'host_cancel') THEN 334
    WHEN (action LIKE 'acculynk_bin_check_failed') THEN 335
    WHEN (action LIKE 'acculynk_pin_pad_error') THEN 336
    WHEN (action LIKE 'custom_recommended_destinations') THEN 337
    WHEN (action LIKE 'this_hosting_reviews_3000') THEN 338
    WHEN (action LIKE 'reset_calendar') THEN 339
    WHEN (action LIKE 'events') THEN 340
    WHEN (action LIKE 'business_travel') THEN 341
    WHEN (action LIKE 'add_guest_colorbox') THEN 342
    WHEN (action LIKE 'hard_fallback_submit') THEN 343
    WHEN (action LIKE 'add_business_address_colorbox') THEN 344
    WHEN (action LIKE 'my_reservations') THEN 345
    WHEN (action LIKE 'report') THEN 346
    WHEN (action LIKE 'book') THEN 347
    WHEN (action LIKE 'revert_to_admin') THEN 348
    WHEN (action LIKE 'acculynk_pin_pad_success') THEN 349
    WHEN (action LIKE 'south-america') THEN 350
    WHEN (action LIKE 'braintree_client_token') THEN 351
    WHEN (action LIKE 'view') THEN 352
    WHEN (action LIKE 'stpcv') THEN 353
    WHEN (action LIKE 'set_minimum_payout_amount') THEN 354
    WHEN (action LIKE 'support_phone_numbers') THEN 355
    WHEN (action LIKE 'refund_guest_cancellation') THEN 356
    WHEN (action LIKE 'accept_decline') THEN 357
    WHEN (action LIKE 'deactivated') THEN 358
    WHEN (action LIKE 'rest-of-world') THEN 359
    ELSE 0
END AS 'action',
CASE
    WHEN (action_type LIKE 'click') THEN 1
    WHEN (action_type LIKE 'data') THEN 2
    WHEN (action_type LIKE 'view') THEN 3
    WHEN (action_type LIKE 'submit') THEN 4
    WHEN (action_type LIKE 'message_post') THEN 5
    WHEN (action_type LIKE '-unknown-') THEN 6
    WHEN (action_type LIKE 'booking_request') THEN 7
    WHEN (action_type LIKE 'partner_callback') THEN 8
    WHEN (action_type LIKE 'booking_response') THEN 9
    WHEN (action_type LIKE 'modify') THEN 10
    ELSE 0
END AS 'action_type',
CASE
    WHEN (action_detail LIKE 'view_search_results') THEN 1
    WHEN (action_detail LIKE 'wishlist_content_update') THEN 2
    WHEN (action_detail LIKE 'similar_listings') THEN 3
    WHEN (action_detail LIKE 'change_trip_characteristics') THEN 4
    WHEN (action_detail LIKE 'p3') THEN 5
    WHEN (action_detail LIKE 'header_userpic') THEN 6
    WHEN (action_detail LIKE 'contact_host') THEN 7
    WHEN (action_detail LIKE 'message_post') THEN 8
    WHEN (action_detail LIKE '-unknown-') THEN 9
    WHEN (action_detail LIKE 'dashboard') THEN 10
    WHEN (action_detail LIKE 'create_user') THEN 11
    WHEN (action_detail LIKE 'confirm_email_link') THEN 12
    WHEN (action_detail LIKE 'user_profile_content_update') THEN 13
    WHEN (action_detail LIKE 'user_profile') THEN 14
    WHEN (action_detail LIKE 'pending') THEN 15
    WHEN (action_detail LIKE 'p5') THEN 16
    WHEN (action_detail LIKE 'create_phone_numbers') THEN 17
    WHEN (action_detail LIKE 'cancellation_policies') THEN 18
    WHEN (action_detail LIKE 'user_wishlists') THEN 19
    WHEN (action_detail LIKE 'change_contact_host_dates') THEN 20
    WHEN (action_detail LIKE 'wishlist') THEN 21
    WHEN (action_detail LIKE 'message_thread') THEN 22
    WHEN (action_detail LIKE 'request_new_confirm_email') THEN 23
    WHEN (action_detail LIKE 'send_message') THEN 24
    WHEN (action_detail LIKE 'your_trips') THEN 25
    WHEN (action_detail LIKE 'login_page') THEN 26
    WHEN (action_detail LIKE 'login') THEN 27
    WHEN (action_detail LIKE 'login_modal') THEN 28
    WHEN (action_detail LIKE 'toggle_archived_thread') THEN 29
    WHEN (action_detail LIKE 'p1') THEN 30
    WHEN (action_detail LIKE 'profile_verifications') THEN 31
    WHEN (action_detail LIKE 'edit_profile') THEN 32
    WHEN (action_detail LIKE 'oauth_login') THEN 33
    WHEN (action_detail LIKE 'post_checkout_action') THEN 34
    WHEN (action_detail LIKE 'account_notification_settings') THEN 35
    WHEN (action_detail LIKE 'update_user_profile') THEN 36
    WHEN (action_detail LIKE 'oauth_response') THEN 37
    WHEN (action_detail LIKE 'signup_modal') THEN 38
    WHEN (action_detail LIKE 'signup_login_page') THEN 39
    WHEN (action_detail LIKE 'at_checkpoint') THEN 40
    WHEN (action_detail LIKE 'manage_listing') THEN 41
    WHEN (action_detail LIKE 'create_listing') THEN 42
    WHEN (action_detail LIKE 'your_listings') THEN 43
    WHEN (action_detail LIKE 'profile_references') THEN 44
    WHEN (action_detail LIKE 'list_your_space') THEN 45
    WHEN (action_detail LIKE 'popular_wishlists') THEN 46
    WHEN (action_detail LIKE 'listing_reviews_page') THEN 47
    WHEN (action_detail LIKE 'apply_coupon') THEN 48
    WHEN (action_detail LIKE 'user_tax_forms') THEN 49
    WHEN (action_detail LIKE 'account_payout_preferences') THEN 50
    WHEN (action_detail LIKE 'guest_itinerary') THEN 51
    WHEN (action_detail LIKE 'guest_receipt') THEN 52
    WHEN (action_detail LIKE 'account_privacy_settings') THEN 53
    WHEN (action_detail LIKE 'lookup_message_thread') THEN 54
    WHEN (action_detail LIKE 'friends_wishlists') THEN 55
    WHEN (action_detail LIKE 'host_guarantee') THEN 56
    WHEN (action_detail LIKE 'delete_phone_numbers') THEN 57
    WHEN (action_detail LIKE 'account_transaction_history') THEN 58
    WHEN (action_detail LIKE 'set_password') THEN 59
    WHEN (action_detail LIKE 'guest_cancellation') THEN 60
    WHEN (action_detail LIKE 'change_or_alter') THEN 61
    WHEN (action_detail LIKE 'your_reservations') THEN 62
    WHEN (action_detail LIKE 'terms_and_privacy') THEN 63
    WHEN (action_detail LIKE 'airbnb_picks_wishlists') THEN 64
    WHEN (action_detail LIKE 'toggle_starred_thread') THEN 65
    WHEN (action_detail LIKE 'email_wishlist') THEN 66
    WHEN (action_detail LIKE 'email_wishlist_button') THEN 67
    WHEN (action_detail LIKE 'wishlist_note') THEN 68
    WHEN (action_detail LIKE 'calculate_worth') THEN 69
    WHEN (action_detail LIKE 'place_worth') THEN 70
    WHEN (action_detail LIKE 'change_password') THEN 71
    WHEN (action_detail LIKE 'alteration_field') THEN 72
    WHEN (action_detail LIKE 'previous_trips') THEN 73
    WHEN (action_detail LIKE 'update_listing') THEN 74
    WHEN (action_detail LIKE 'update_listing_description') THEN 75
    WHEN (action_detail LIKE 'user_reviews') THEN 76
    WHEN (action_detail LIKE 'update_user') THEN 77
    WHEN (action_detail LIKE 'notifications') THEN 78
    WHEN (action_detail LIKE 'user_social_connections') THEN 79
    WHEN (action_detail LIKE 'unavailable_dates') THEN 80
    WHEN (action_detail LIKE 'reservations') THEN 81
    WHEN (action_detail LIKE 'listing_reviews') THEN 82
    WHEN (action_detail LIKE 'user_listings') THEN 83
    WHEN (action_detail LIKE 'signup') THEN 84
    WHEN (action_detail LIKE 'message_inbox') THEN 85
    WHEN (action_detail LIKE 'trip_availability') THEN 86
    WHEN (action_detail LIKE 'payment_instruments') THEN 87
    WHEN (action_detail LIKE 'admin_templates') THEN 88
    WHEN (action_detail LIKE 'host_home') THEN 89
    WHEN (action_detail LIKE 'translations') THEN 90
    WHEN (action_detail LIKE 'forgot_password') THEN 91
    WHEN (action_detail LIKE 'remove_dashboard_alert') THEN 92
    WHEN (action_detail LIKE 'user_friend_recommendations') THEN 93
    WHEN (action_detail LIKE 'confirm_email') THEN 94
    WHEN (action_detail LIKE 'host_respond') THEN 95
    WHEN (action_detail LIKE 'booking') THEN 96
    WHEN (action_detail LIKE 'respond_to_alteration_request') THEN 97
    WHEN (action_detail LIKE 'alteration_request') THEN 98
    WHEN (action_detail LIKE 'create_alteration_request') THEN 99
    WHEN (action_detail LIKE 'delete_listing') THEN 100
    WHEN (action_detail LIKE 'set_password_page') THEN 101
    WHEN (action_detail LIKE 'homepage') THEN 102
    WHEN (action_detail LIKE 'delete_listing_description') THEN 103
    WHEN (action_detail LIKE 'translate_listing_reviews') THEN 104
    WHEN (action_detail LIKE 'book_it') THEN 105
    WHEN (action_detail LIKE 'instant_book') THEN 106
    WHEN (action_detail LIKE 'request_to_book') THEN 107
    WHEN (action_detail LIKE 'complete_booking') THEN 108
    WHEN (action_detail LIKE 'change_availability') THEN 109
    WHEN (action_detail LIKE 'special_offer_field') THEN 110
    WHEN (action_detail LIKE 'listing_recommendations') THEN 111
    WHEN (action_detail LIKE 'view_listing') THEN 112
    WHEN (action_detail LIKE 'listing_descriptions') THEN 113
    WHEN (action_detail LIKE 'user_languages') THEN 114
    WHEN (action_detail LIKE 'p4') THEN 115
    WHEN (action_detail LIKE 'message_to_host_focus') THEN 116
    WHEN (action_detail LIKE 'cancellation_policy_click') THEN 117
    WHEN (action_detail LIKE 'message_to_host_change') THEN 118
    WHEN (action_detail LIKE 'read_policy_click') THEN 119
    WHEN (action_detail LIKE 'phone_verification_success') THEN 120
    WHEN (action_detail LIKE 'p4_refund_policy_terms') THEN 121
    WHEN (action_detail LIKE 'apply_coupon_error') THEN 122
    WHEN (action_detail LIKE 'apply_coupon_click') THEN 123
    WHEN (action_detail LIKE 'coupon_field_focus') THEN 124
    WHEN (action_detail LIKE 'coupon_code_click') THEN 125
    WHEN (action_detail LIKE 'p4_terms') THEN 126
    WHEN (action_detail LIKE 'apply_coupon_click_success') THEN 127
    WHEN (action_detail LIKE 'tos_2014') THEN 128
    WHEN (action_detail LIKE 'view_reservations') THEN 129
    WHEN (action_detail LIKE 'view_locations') THEN 130
    WHEN (action_detail LIKE 'modify_users') THEN 131
    WHEN (action_detail LIKE 'view_security_checks') THEN 132
    WHEN (action_detail LIKE 'phone_numbers') THEN 133
    WHEN (action_detail LIKE 'profile_reviews') THEN 134
    WHEN (action_detail LIKE 'modify_reservations') THEN 135
    WHEN (action_detail LIKE 'view_resolutions') THEN 136
    WHEN (action_detail LIKE 'account_payment_methods') THEN 137
    WHEN (action_detail LIKE 'create_payment_instrument') THEN 138
    WHEN (action_detail LIKE 'set_default_payment_instrument') THEN 139
    WHEN (action_detail LIKE 'delete_payment_instrument') THEN 140
    WHEN (action_detail LIKE 'photos') THEN 141
    WHEN (action_detail LIKE 'click_reviews') THEN 142
    WHEN (action_detail LIKE 'move_map') THEN 143
    WHEN (action_detail LIKE 'share') THEN 144
    WHEN (action_detail LIKE 'cancellation_policy') THEN 145
    WHEN (action_detail LIKE 'click_about_host') THEN 146
    WHEN (action_detail LIKE 'click_amenities') THEN 147
    WHEN (action_detail LIKE 'host_refund_guest') THEN 148
    WHEN (action_detail LIKE 'host_respond_page') THEN 149
    WHEN (action_detail LIKE 'view_user_real_names') THEN 150
    WHEN (action_detail LIKE 'view_identity_verifications') THEN 151
    WHEN (action_detail LIKE 'view_ghosting_reasons') THEN 152
    WHEN (action_detail LIKE 'view_ghostings') THEN 153
    WHEN (action_detail LIKE 'host_standard_suspension') THEN 154
    WHEN (action_detail LIKE 'deactivate_user_account') THEN 155
    ELSE 0
END AS 'action_detail',
CASE
    WHEN (device_type LIKE 'Windows Desktop') THEN 1
    WHEN (device_type LIKE '-unknown-') THEN 2
    WHEN (device_type LIKE 'Mac Desktop') THEN 3
    WHEN (device_type LIKE 'Android Phone') THEN 4
    WHEN (device_type LIKE 'iPhone') THEN 5
    WHEN (device_type LIKE 'iPad Tablet') THEN 6
    WHEN (device_type LIKE 'Android App Unknown Phone/Tablet') THEN 7
    WHEN (device_type LIKE 'Linux Desktop') THEN 8
    WHEN (device_type LIKE 'Tablet') THEN 9
    WHEN (device_type LIKE 'Chromebook') THEN 10
    WHEN (device_type LIKE 'Blackberry') THEN 11
    WHEN (device_type LIKE 'iPodtouch') THEN 12
    WHEN (device_type LIKE 'Windows Phone') THEN 13
    WHEN (device_type LIKE 'Opera Phone') THEN 14
    ELSE 0
END AS 'device_type'
FROM sessions)
TO '/var/lib/postgresql/sessions_tratado.csv'
DELIMITER ','
CSV HEADER;
